(defvar file-icon-alist
  '(
    ("elisp" . "\xe926")
    ("git" . "\xe602")
    ("docker" . "\xf106")
    ("babel" . "\xe91f")
    ("eslint" . "\xe90e")
    ("perl6" . "\xe96c")
    ("php" . "\xf147")
    ("jsx" . "\xf101")
    ("javascript" . "\x1f5cc")
    ("npm" . "\xe91c")
    ("apple" . "\xe925")
    ("audacity" . "\xe9f9")
    ("bib" . "\xe601")
    ("lisp" . "\xe908")
    ("clisp" . "\xe972")
    ("font" . "\xe90f")
    ("haml" . "\xf15b")
    ("jade" . "\xe90d")
    ("pug" . "\xe9d0")
    ("presentation" . "\xe9e5")
    ("node" . "\xe618")
    ("react" . "\xf100")
    ("julia" . "\x26ec")
    ("tex" . "\xe600")
    ("org" . "\xe917")
    ("nginx" . "\xf146b")
    ("less" . "{}")
    ("postcss" . "\xe910")
    ("scheme" . "\x03bb")
    ("stylelint" . "\xe93d")
    ("matlab" . "\xe991")
    ("pony" . "\xe9b7")
    ("R" . "\xe905")
    ("word" . "\xe9ed")
    ("ppt" . "\xe9ec")
    ))

(provide 'data-fileicons)
